version: '3.7'

services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@127.0.0.1:1521/ORCLCDB
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - my-database

  my-database:
    image: oracle/database:19.3.0-ee
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: 1234
    ports:
      - 1521:1521
